# Generated by Django 2.1 on 2019-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_login', models.CharField(max_length=500)),
                ('no_of_commits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='url',
            field=models.ManyToManyField(to='search_repo.History'),
        ),
    ]
