# Generated by Django 2.1 on 2019-10-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_commits', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='no_of_commits',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='url',
        ),
        migrations.AddField(
            model_name='contributor',
            name='url',
            field=models.ForeignKey(default=-2018, on_delete=django.db.models.deletion.CASCADE, to='search_repo.History'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='con',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_repo.Contributor'),
        ),
    ]
