# Generated by Django 2.1 on 2019-10-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_repo', '0003_contributor_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='con',
            new_name='contributor',
        ),
    ]
